apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-szew
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zzop-tenant/rhtap-demo-app/hacbs-test-project-szew@sha256:5c8ea4807fa3a380813800382b75438450f7cbfed4b7406ce4d767fd537601fb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
